/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../common";

export interface TradePlatformInterface extends utils.Interface {
  functions: {
    "INITIAL_TOKEN_AMOUNT()": FunctionFragment;
    "_balances(address)": FunctionFragment;
    "buyACDM()": FunctionFragment;
    "endsAt()": FunctionFragment;
    "register(address)": FunctionFragment;
    "roundStatus()": FunctionFragment;
    "roundTime()": FunctionFragment;
    "startSaleRound()": FunctionFragment;
    "startTradeRound()": FunctionFragment;
    "startsAt()": FunctionFragment;
    "token()": FunctionFragment;
    "tokenPrice()": FunctionFragment;
    "tokens()": FunctionFragment;
    "tradeStock()": FunctionFragment;
    "users(address)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "INITIAL_TOKEN_AMOUNT"
      | "_balances"
      | "buyACDM"
      | "endsAt"
      | "register"
      | "roundStatus"
      | "roundTime"
      | "startSaleRound"
      | "startTradeRound"
      | "startsAt"
      | "token"
      | "tokenPrice"
      | "tokens"
      | "tradeStock"
      | "users"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "INITIAL_TOKEN_AMOUNT",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "_balances", values: [string]): string;
  encodeFunctionData(functionFragment: "buyACDM", values?: undefined): string;
  encodeFunctionData(functionFragment: "endsAt", values?: undefined): string;
  encodeFunctionData(functionFragment: "register", values: [string]): string;
  encodeFunctionData(
    functionFragment: "roundStatus",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "roundTime", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "startSaleRound",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "startTradeRound",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "startsAt", values?: undefined): string;
  encodeFunctionData(functionFragment: "token", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "tokenPrice",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "tokens", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "tradeStock",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "users", values: [string]): string;

  decodeFunctionResult(
    functionFragment: "INITIAL_TOKEN_AMOUNT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "_balances", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "buyACDM", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "endsAt", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "register", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "roundStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "roundTime", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "startSaleRound",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "startTradeRound",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "startsAt", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "token", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "tokenPrice", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "tokens", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "tradeStock", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "users", data: BytesLike): Result;

  events: {};
}

export interface TradePlatform extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: TradePlatformInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    INITIAL_TOKEN_AMOUNT(overrides?: CallOverrides): Promise<[BigNumber]>;

    _balances(arg0: string, overrides?: CallOverrides): Promise<[BigNumber]>;

    buyACDM(
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    endsAt(overrides?: CallOverrides): Promise<[BigNumber]>;

    register(
      _referer: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    roundStatus(overrides?: CallOverrides): Promise<[number]>;

    roundTime(overrides?: CallOverrides): Promise<[BigNumber]>;

    startSaleRound(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    startTradeRound(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    startsAt(overrides?: CallOverrides): Promise<[BigNumber]>;

    token(overrides?: CallOverrides): Promise<[string]>;

    tokenPrice(overrides?: CallOverrides): Promise<[BigNumber]>;

    tokens(overrides?: CallOverrides): Promise<[BigNumber]>;

    tradeStock(overrides?: CallOverrides): Promise<[BigNumber]>;

    users(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, string, boolean, boolean] & {
        amountOfACDM: BigNumber;
        referer: string;
        isReferer: boolean;
        isExists: boolean;
      }
    >;
  };

  INITIAL_TOKEN_AMOUNT(overrides?: CallOverrides): Promise<BigNumber>;

  _balances(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

  buyACDM(
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  endsAt(overrides?: CallOverrides): Promise<BigNumber>;

  register(
    _referer: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  roundStatus(overrides?: CallOverrides): Promise<number>;

  roundTime(overrides?: CallOverrides): Promise<BigNumber>;

  startSaleRound(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  startTradeRound(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  startsAt(overrides?: CallOverrides): Promise<BigNumber>;

  token(overrides?: CallOverrides): Promise<string>;

  tokenPrice(overrides?: CallOverrides): Promise<BigNumber>;

  tokens(overrides?: CallOverrides): Promise<BigNumber>;

  tradeStock(overrides?: CallOverrides): Promise<BigNumber>;

  users(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, string, boolean, boolean] & {
      amountOfACDM: BigNumber;
      referer: string;
      isReferer: boolean;
      isExists: boolean;
    }
  >;

  callStatic: {
    INITIAL_TOKEN_AMOUNT(overrides?: CallOverrides): Promise<BigNumber>;

    _balances(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    buyACDM(overrides?: CallOverrides): Promise<void>;

    endsAt(overrides?: CallOverrides): Promise<BigNumber>;

    register(_referer: string, overrides?: CallOverrides): Promise<void>;

    roundStatus(overrides?: CallOverrides): Promise<number>;

    roundTime(overrides?: CallOverrides): Promise<BigNumber>;

    startSaleRound(overrides?: CallOverrides): Promise<void>;

    startTradeRound(overrides?: CallOverrides): Promise<void>;

    startsAt(overrides?: CallOverrides): Promise<BigNumber>;

    token(overrides?: CallOverrides): Promise<string>;

    tokenPrice(overrides?: CallOverrides): Promise<BigNumber>;

    tokens(overrides?: CallOverrides): Promise<BigNumber>;

    tradeStock(overrides?: CallOverrides): Promise<BigNumber>;

    users(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, string, boolean, boolean] & {
        amountOfACDM: BigNumber;
        referer: string;
        isReferer: boolean;
        isExists: boolean;
      }
    >;
  };

  filters: {};

  estimateGas: {
    INITIAL_TOKEN_AMOUNT(overrides?: CallOverrides): Promise<BigNumber>;

    _balances(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    buyACDM(
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    endsAt(overrides?: CallOverrides): Promise<BigNumber>;

    register(
      _referer: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    roundStatus(overrides?: CallOverrides): Promise<BigNumber>;

    roundTime(overrides?: CallOverrides): Promise<BigNumber>;

    startSaleRound(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    startTradeRound(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    startsAt(overrides?: CallOverrides): Promise<BigNumber>;

    token(overrides?: CallOverrides): Promise<BigNumber>;

    tokenPrice(overrides?: CallOverrides): Promise<BigNumber>;

    tokens(overrides?: CallOverrides): Promise<BigNumber>;

    tradeStock(overrides?: CallOverrides): Promise<BigNumber>;

    users(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    INITIAL_TOKEN_AMOUNT(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    _balances(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    buyACDM(
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    endsAt(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    register(
      _referer: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    roundStatus(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    roundTime(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    startSaleRound(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    startTradeRound(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    startsAt(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    token(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    tokenPrice(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    tokens(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    tradeStock(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    users(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
